# .github/workflows/deploy.yml
name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем код
      - uses: actions/checkout@v3

      # 2. Поднимаем нужную версию Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci

      # 4. Собираем проект в production-режиме
      - name: Build production bundle
        run: npm run build -- --configuration production --base-href=/mapbox-track/

      # 5. Деплоим на ветку gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # автоматически возьмёт токен из SECRET.GITHUB_TOKEN
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Путь к артефактам сборки
          publish_dir: ./dist/mapbox-track
          # Желательно явно указать ветку, но по умолчанию это gh-pages
          publish_branch: gh-pages
