name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master    # или ваша основная ветка

permissions:
  contents: write   # чтобы GITHUB_TOKEN мог пушить в gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        # Здесь используем ваш скрипт, который ставит base-href и кладёт всё в dist/mapbox-track
        run: npm run build:gh

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/mapbox-track
          publish_branch: gh-pages
