name: Deploy Angular App to GitHub Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build for production
        run: |
          npm run build:gh
          # Проверяем, что сборка прошла успешно
          if [ ! -d "dist/mapbox-track" ]; then
            echo "❌ Error: dist/mapbox-track directory not found after build!"
            ls -R dist
            exit 1
          fi

      - name: Verify build output
        run: |
          echo "Build contents:"
          ls -la dist/mapbox-track
          if [ ! -f "dist/mapbox-track/index.html" ]; then
            echo "❌ Error: index.html not found in dist/mapbox-track!"
            exit 1
          fi

      - name: Prepare for GitHub Pages
        run: |
          cd dist/mapbox-track
          # Создаем 404.html для SPA
          echo '<!DOCTYPE html>
          <html>
            <head>
              <script>
                sessionStorage.redirect = location.pathname;
                location.replace("/mapbox-track/");
              </script>
            </head>
            <body>
              Redirecting...
            </body>
          </html>' > 404.html
          
          # Модифицируем base href только если файл существует
          if [ -f "index.html" ]; then
            sed -i 's|<base href="/">|<base href="/mapbox-track/">|' index.html
            echo "✅ Successfully modified base href"
          else
            echo "❌ Error: index.html not found!"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/mapbox-track
          publish_branch: gh-pages
          enable_jekyll: false
          keep_files: false
          force_orphan: true