# .github/workflows/deploy.yml
name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master      # ваша default-ветка
  workflow_dispatch: {}

permissions:
  contents: write  # чтобы GITHUB_TOKEN мог пушить в репо

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build production bundle
        # скрипт build:gh теперь делает ng build --configuration=production
        run: npm run build:gh

         - name: Find index.html
        run: |
          echo "Looking for index.html under dist/mapbox-track…"
          find dist/mapbox-track -type f -name index.html || echo "❌ index.html not found"

      - name: Verify build output
        run: |
          echo "Contents of dist/mapbox-track:"
          ls -R dist/mapbox-track
          if [ ! -f "dist/mapbox-track/index.html" ]; then
            echo "❌ Error: index.html not found in dist/mapbox-track!"
            exit 1
          fi

      - name: Prepare SPA 404 fallback
        run: |
          cd dist/mapbox-track
          cat > 404.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8" />
              <script>
                // При заходе на любую вложенную ссылку
                // перенаправляем на корень, Angular сам прочитает URL
                const path = window.location.pathname;
                sessionStorage.setItem('redirect', path);
                location.replace('/mapbox-track/');
              </script>
            </head>
            <body>
              Redirecting...
            </body>
          </html>
          EOF

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/mapbox-track
          publish_branch: gh-pages
          enable_jekyll: false
          keep_files: false
          force_orphan: true
