# .github/workflows/deploy.yml
name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master      # или ваша основная ветка
  workflow_dispatch: {}

permissions:
  contents: write  # даём GITHUB_TOKEN право пушить в репозиторий

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build production bundle
        run: npm run build:gh

      - name: List build output
        run: |
          echo "Contents of dist/mapbox-track:"
          ls -R dist/mapbox-track

      - name: Determine publish directory
        run: |
          # Если index.html в корне dist/mapbox-track
          if [ -f dist/mapbox-track/index.html ]; then
            echo "PUBLISH_DIR=dist/mapbox-track" >> $GITHUB_ENV
          # Если используется prerender и index.html лежит в browser/
          elif [ -f dist/mapbox-track/browser/index.html ]; then
            echo "PUBLISH_DIR=dist/mapbox-track/browser" >> $GITHUB_ENV
          else
            echo "❌ index.html not found in dist/mapbox-track!" >&2
            exit 1
          fi

      - name: Prepare SPA 404 fallback
        run: |
          cd "${PUBLISH_DIR}"
          cat > 404.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8" />
              <script>
                // При заходе на вложенный URL запомним путь и вернёмся на корень
                const path = window.location.pathname;
                sessionStorage.setItem('redirect', path);
                location.replace("/mapbox-track/");
              </script>
            </head>
            <body>
              Redirecting...
            </body>
          </html>
          EOF

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.PUBLISH_DIR }}
          publish_branch: gh-pages
          enable_jekyll: false
          keep_files: false
          force_orphan: true
